#!/bin/sh

dir=$(dirname $0)

olddir=$(pwd)
cd $dir/cli
git pull origin master

echo -e "\nCompiling and Stripping"
./build -static -no-pie || exit 1

echo -e "\nPackaging"
folder="tinynx-$(./nx -v)-"
folder="${folder}$(gcc -dumpmachine)"

mkdir -p "$folder"
mv ./nx $folder/nx
git archive HEAD --prefix=src/ -o "$folder"/src.tar
cd "$folder"
tar xf src.tar
cd ..

rm "$folder".tar.xz
tar -cvJf "$folder".tar.xz \
    "$folder"/nx \
    "$folder"/src

echo -e "\nResult:"
tar tf "$folder".tar.xz

readelf --dynamic "$folder"/nx
ldd "$folder"/nx

rm -rf "$folder"
cd $olddir

